# Pre-process Multibarcode input for BMI

In [2]:
import pandas as pd

In [14]:
full_mb_df = pd.read_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl/bmi_multibarcode_input.tsv", sep="\t", header=None)
new_column_names = ['seq_id', 'primer', 'scientific_name', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species', 'seq']
full_mb_df.columns = new_column_names[:len(full_mb_df.columns)]
full_mb_df

,seq_id,primer,scientific_name,kingdom,phylum,class,order,family,genus,species,seq
0,AAGRE003-21,COI_mICOIintF_jgHCO2198,Atylotus agrestis Wiedemann 1828,Animalia,Arthropoda,Insecta,Diptera,Tabanidae,Atylotus,Atylotus agrestis,CCTATCTGCTGCAATTGCCCATGGAGGAGGTTCTGTTGATTTAGCA...
1,ABEE097-17,COI_mICOIintF_jgHCO2198,Andrena pilipes Fabricius 1781,Animalia,Arthropoda,Insecta,Hymenoptera,Andrenidae,Andrena,Andrena pilipes,ATTATCATCATATTCTTATCACCCATCTTCCTCAACAGACCTAACA...
2,ABEE104-17,COI_mICOIintF_jgHCO2198,Halictus quadricinctus Fabricius 1776,Animalia,Arthropoda,Insecta,Hymenoptera,Halictidae,Halictus,Halictus quadricinctus,TCTATCATCAATTATATTTCATGCATCTTTCTCTGTTGATTTTTCT...
3,ABEE111-17,COI_mICOIintF_jgHCO2198,Hylaeus sinuatus Schenck 1853,Animalia,Arthropoda,Insecta,Hymenoptera,Colletidae,Hylaeus,Hylaeus sinuatus,CTTATCATCCATAATATATCATCCATCATTATCAGTTGATTTAACA...
4,ABEE126-17,COI_mICOIintF_jgHCO2198,Hylaeus cornutus Curtis 1831,Animalia,Arthropoda,Insecta,Hymenoptera,Colletidae,Hylaeus,Hylaeus cornutus,ATTATCATCAATAATATACCATCCATCATTATCAGTAGATTTTACA...
...,...,...,...,...,...,...,...,...,...,...,...
3702182,DEEUR600-16,COI_FwhF2_FwhR2n,Agonopterix squamosa Mann 1864,Animalia,Arthropoda,Insecta,Lepidoptera,Depressariidae,Agonopterix,Agonopterix squamosa,ACTTTCATCTAATATTGCCCATGGAGGTAGATCAGTAGATCTAGCT...
3702183,GMACB361-15,COI_FwhF2_FwhR2n,Megaselia Rondani 1856,Animalia,Arthropoda,Insecta,Diptera,Phoridae,Megaselia,NaN,CCTTTCTTCTAATATTGCTCATAGAGGAGCCTCTGTAGATTTAGCA...
3702184,TSZJK864-19,COI_FwhF2_FwhR2n,Phronia forcipata Winnertz 1863,Animalia,Arthropoda,Insecta,Diptera,Mycetophilidae,Phronia,Phronia forcipata,CCTTTCTTCGACTATTGCTCATGCTGGTGCATCAGTTGATTTAGCT...
3702185,HPPPE1777-13,COI_FwhF2_FwhR2n,Ancistrocerus adiabatus de Saussure 1853,Animalia,Arthropoda,Insecta,Hymenoptera,Vespidae,Ancistrocerus,Ancistrocerus adiabatus,TTTATCTTNTATTACAGGTCACAATTCTCCTTCTGTAGATTTTGGT...
3702186,GMIAA1303-18,COI_FwhF2_FwhR2n,Ceratopogonidae,Animalia,Arthropoda,Insecta,Diptera,Ceratopogonidae,NaN,NaN,CCTCTCATCTAATATTTCTCATGCCGGTGCATCAGTAGACTTTGCT...

## Evaluate subset volume

### Per primer

In [15]:
unique_primers = full_mb_df.groupby('primer').size()
unique_primers.sort_values(ascending=False)

primer
COI_FwhF2_FwhR2n             608745
COI_BF3_BR2                  499618
COI_BF2_BR2                  499587
COI_fwhF2_Fol-degen-rev      493278
COI_mICOIintF_jgHCO2198      492918
COI_MICOIntF_HCO2198         492094
COI_FwhF2_EPTDr2n            382051
COI_MG2-LCO1490_MG2-univR    233896
dtype: int64

In [16]:
primer_df = full_mb_df[full_mb_df['primer'] == 'COI_FwhF2_FwhR2n']
primer_df
# primer_df = primer_df[['seq_id', 'primer', 'scientific_name', 'seq']]
# primer_df
# primer_df.to_csv("fwh.tsv", sep="\t", index=False)

,seq_id,primer,scientific_name,kingdom,phylum,class,order,family,genus,species,seq
406754,AASFB602-10,COI_FwhF2_FwhR2n,Ctenidae,Animalia,Arthropoda,Arachnida,Araneae,Ctenidae,NaN,NaN,TTTAGCTTCTAGAGTAGGTCATATAGGAAGATCAATGGATTTTGCT...
406755,AASFB633-10,COI_FwhF2_FwhR2n,Clubionidae,Animalia,Arthropoda,Arachnida,Araneae,Clubionidae,NaN,NaN,TTTAGCTTCTGGCGTGGGACATTCTGGTAGTGCTATGGATTTTGCT...
406756,AASFB645-10,COI_FwhF2_FwhR2n,Anyphaenidae,Animalia,Arthropoda,Arachnida,Araneae,Anyphaenidae,NaN,NaN,TTTATCTTCAAGAGTTGGTCATATAGGAAGAGCTATAGATTTTGCT...
406757,AASFB649-10,COI_FwhF2_FwhR2n,Corinnidae,Animalia,Arthropoda,Arachnida,Araneae,Corinnidae,NaN,NaN,TTTAGCATCAACTATAGGGCACACAGGAAGAGCTGTTGATTTTGCG...
406758,AASFB654-10,COI_FwhF2_FwhR2n,Salticidae,Animalia,Arthropoda,Arachnida,Araneae,Salticidae,NaN,NaN,TTTAGCTTCAATTGTTGGGCATAATGGAAGTTCTGTTGATTTTGCA...
...,...,...,...,...,...,...,...,...,...,...,...
3702182,DEEUR600-16,COI_FwhF2_FwhR2n,Agonopterix squamosa Mann 1864,Animalia,Arthropoda,Insecta,Lepidoptera,Depressariidae,Agonopterix,Agonopterix squamosa,ACTTTCATCTAATATTGCCCATGGAGGTAGATCAGTAGATCTAGCT...
3702183,GMACB361-15,COI_FwhF2_FwhR2n,Megaselia Rondani 1856,Animalia,Arthropoda,Insecta,Diptera,Phoridae,Megaselia,NaN,CCTTTCTTCTAATATTGCTCATAGAGGAGCCTCTGTAGATTTAGCA...
3702184,TSZJK864-19,COI_FwhF2_FwhR2n,Phronia forcipata Winnertz 1863,Animalia,Arthropoda,Insecta,Diptera,Mycetophilidae,Phronia,Phronia forcipata,CCTTTCTTCGACTATTGCTCATGCTGGTGCATCAGTTGATTTAGCT...
3702185,HPPPE1777-13,COI_FwhF2_FwhR2n,Ancistrocerus adiabatus de Saussure 1853,Animalia,Arthropoda,Insecta,Hymenoptera,Vespidae,Ancistrocerus,Ancistrocerus adiabatus,TTTATCTTNTATTACAGGTCACAATTCTCCTTCTGTAGATTTTGGT...
3702186,GMIAA1303-18,COI_FwhF2_FwhR2n,Ceratopogonidae,Animalia,Arthropoda,Insecta,Diptera,Ceratopogonidae,NaN,NaN,CCTCTCATCTAATATTTCTCATGCCGGTGCATCAGTAGACTTTGCT...

In [ ]:
# for primer in unique_primers.keys():
#     primer_df = full_mb_df[full_mb_df['primer'] == primer]
#     primer_df = primer_df[['seq_id', 'primer', 'scientific_name', 'seq']]
#     output_path = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-test-pipeline/multibarcode/mb_subset_" + primer + ".tsv"
#     primer_df.to_csv(output_path, sep="\t", index=False, header=None)

### Per Family

In [17]:
unique_families = full_mb_df.groupby('family').size()
unique_families.sort_values(ascending=False)

family
Cecidomyiidae         388069
Chironomidae          322583
Ceratopogonidae       154400
Sciaridae             134253
Staphylinidae         100794
                       ...
Desmarestiaceae            1
Bryocryptellidae           1
Mesosignidae               1
Metopidiotrichidae         1
Eriopisidae                1
Length: 2138, dtype: int64

In [18]:
primer_df = full_mb_df[full_mb_df['primer'] == 'COI_FwhF2_FwhR2n']
unique_fam_prim = primer_df.groupby('family').size()
unique_fam_prim.sort_values(ascending=False)

family
Cecidomyiidae        66356
Chironomidae         46389
Ceratopogonidae      23311
Sciaridae            21998
Staphylinidae        16090
                     ...
Acroporidae              1
Ustyurtiidae             1
Acteonidae               1
Acropsopilionidae        1
Lychnocolacidae          1
Length: 2102, dtype: int64

In [20]:
primer_subset = full_mb_df[full_mb_df['primer'] == 'COI_FwhF2_FwhR2n']
test_subset = primer_subset[full_mb_df['family'] == 'Chironomidae']
test_subset = test_subset[['seq_id', 'primer', 'scientific_name', 'seq']]
test_subset
test_subset.to_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-phyl/mulitbarcode/Chironomidae_fwh.tsv", sep='\t', index=False)

/tmp/ipykernel_29479/1216577399.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  test_subset = primer_subset[full_mb_df['family'] == 'Chironomidae']

### Per Order

In [ ]:
primer_df = full_mb_df[full_mb_df['primer'] == 'COI_FwhF2_FwhR2n']
unique_orders = primer_df.groupby('order').size()
unique_orders.sort_values(ascending=False)

order
Diptera           260984
Hymenoptera        82758
Coleoptera         81625
Lepidoptera        62315
Hemiptera          32882
                   ...
Solemyida              1
Tethyida               1
Sphacelariales         1
Verongiida             1
Zoraptera              1
Length: 209, dtype: int64

In [ ]:
# # Count instances with a value of 1
orders_with_one_entry = unique_orders[unique_orders == 1]
orders_with_one_entry

order
Ahnfeltiales       1
Coronatae          1
Cyclophyllidea     1
Desmacellida       1
Desmarestiales     1
Grylloblattodea    1
Leptostraca        1
Leucosolenida      1
Lyssacinosida      1
Parvidrilida       1
Plocamiales        1
Solemyida          1
Sphacelariales     1
Tethyida           1
Verongiida         1
Zoraptera          1
dtype: int64

In [ ]:
prim_order =  primer_df[primer_df['order'] == 'Lepidoptera']
prim_order = prim_order[['seq_id', 'primer', 'scientific_name', 'seq']]
prim_order
prim_order.to_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-test-pipeline/multibarcode/Lepidoptera-fwh.tsv", sep='\t', index=False, header=None)

#### Clustered

In [ ]:
# Input df
primer_df = full_mb_df[full_mb_df['primer'] == 'COI_FwhF2_FwhR2n']
largest_prim_order =  primer_df[primer_df['order'] == 'Diptera']
largest_prim_order = largest_prim_order[['seq_id', 'primer', 'scientific_name', 'family', 'genus', 'species','seq']]
largest_prim_order
# largest_prim_order.to_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-test-pipeline/multibarcode/diptera-fwh-taxonomy-multiabrcode.tsv", sep='\t', index=False, header=None)

,seq_id,primer,scientific_name,family,genus,species,seq
406989,AAASF032-17,COI_FwhF2_FwhR2n,Dampfomyia deleoni Fairchild Hertig 1948,Psychodidae,Dampfomyia,Dampfomyia deleoni,TTTATCAAGTAATATTGCACATAGAGGTGCCTCTGTTGATCTTGCA...
406990,AAASF015-17,COI_FwhF2_FwhR2n,Dampfomyia deleoni Fairchild Hertig 1948,Psychodidae,Dampfomyia,Dampfomyia deleoni,TTTATCAAGTAATATTGCACATAGAGGTGCCTCTGTTGATCTTGCA...
406991,AAASF019-17,COI_FwhF2_FwhR2n,Dampfomyia deleoni Fairchild Hertig 1948,Psychodidae,Dampfomyia,Dampfomyia deleoni,TTTATCAAGTAATATTGCACATAGAGGTGCCTCTGTTGATCTTGCA...
406992,AAASF029-17,COI_FwhF2_FwhR2n,Dampfomyia deleoni Fairchild Hertig 1948,Psychodidae,Dampfomyia,Dampfomyia deleoni,TTTATCAAGTAATATTGCACATAGAGGTGCCTCTGTTGATCTTGCA...
406993,AAASF007-17,COI_FwhF2_FwhR2n,Lutzomyia longipalpis Lutz Neiva 1912,Psychodidae,Lutzomyia,Lutzomyia longipalpis,TTTATCTAGAAATATTGCCCATAGAGGAGCTTCAGTTGATTTAGCA...
...,...,...,...,...,...,...,...
3703044,CNGSD5231-15,COI_FwhF2_FwhR2n,Coelosynapha heberti Kjaerandsen 2020,Mycetophilidae,Coelosynapha,Coelosynapha heberti,CTTATCTTCAACTATTGCTCATGCTGGAGCTTCGGTAGATTTAGCT...
3703046,SSBAE6126-13,COI_FwhF2_FwhR2n,Keroplatidae,Keroplatidae,NaN,NaN,TCTTTCAACTACTATTTCTCATTCTGGTGCATCTGTAGATTTAGCT...
3703058,GBMTM846-15,COI_FwhF2_FwhR2n,Chloropidae,Chloropidae,NaN,NaN,ACTATCTTCAATTATTGCACATGGAGGAGCTTCTGTTGATTTAGCT...
3703062,JICCR615-16,COI_FwhF2_FwhR2n,Simulium tarsatum Macquart 1846,Simuliidae,Simulium,Simulium tarsatum,TCTTTCTTCGGGTATTGCTCATGCTGGAGCCTCAGTTGATTTAGCA...
3703066,GMACB673-15,COI_FwhF2_FwhR2n,Sciaridae,Sciaridae,NaN,NaN,TTTATCAATAAATATTGCTCACTCAGGACCATCAATTGACTTATCA...

In [25]:
# Clustered df
diptera_clts = pd.read_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-test-pipeline/multibarcode/diptera_clustered.csv", sep='\t')
diptera_clts = diptera_clts[['processid', 'primer', 'scientific_name','seq']]
diptera_clts.rename(columns={"processid": "seq_id"})
diptera_clts
# diptera_clts.to_csv("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-test-pipeline/multibarcode/diptera_clustered_clean.tsv", sep='\t', index=False, header=None)

,processid,primer,scientific_name,seq
0,AAASF032-17,COI_FwhF2_FwhR2n,Dampfomyia deleoni Fairchild Hertig 1948,TTTATCAAGTAATATTGCACATAGAGGTGCCTCTGTTGATCTTGCA...
1,AAASF007-17,COI_FwhF2_FwhR2n,Lutzomyia longipalpis Lutz Neiva 1912,TTTATCTAGAAATATTGCCCATAGAGGAGCTTCAGTTGATTTAGCA...
2,AACTA199-20,COI_FwhF2_FwhR2n,Sciaridae,TTTATCTTCAACTATTGCTCATTCAGGAGGATCGGTTGATTTATCA...
3,AAASF035-18,COI_FwhF2_FwhR2n,Brumptomyia mesai Sherlock 1962,TTTATCAAGTAATATTGCTCATGGGGGGGCATCTGTAGACTTAGCA...
4,AAASF036-18,COI_FwhF2_FwhR2n,Dampfomyia beltrani Vargas Diaz Najera 1951,CTTATCAAGCAATATTGCCCATAGAGGAGCCTCTGTTGATTTAGCT...
...,...,...,...,...
104055,GMACB1160-15,COI_FwhF2_FwhR2n,Hyperlasion Schmitz 1918,TCTTTCATCAATTGAATTTCATTCAAGAGCATCAGTAGATTTATCA...
104056,GMIAD238-17,COI_FwhF2_FwhR2n,Lauxaniidae,TCTTTCTTCAGGGATTGCACATGGAGGAGCATCAGTAGATTTAGCA...
104057,GMIAF594-17,COI_FwhF2_FwhR2n,Cecidomyiidae,TCTTTCATCTGTAATTGCCCATACTGGATCTTCAGTAGACTTTTCA...
104058,GBMTM846-15,COI_FwhF2_FwhR2n,Chloropidae,ACTATCTTCAATTATTGCACATGGAGGAGCTTCTGTTGATTTAGCT...
104059,JICCR615-16,COI_FwhF2_FwhR2n,Simulium tarsatum Macquart 1846,TCTTTCTTCGGGTATTGCTCATGCTGGAGCCTCAGTTGATTTAGCA...

In [ ]:
# with open("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi-600k/insert/filtered/multibarcode/fwh_diptera.fasta", "w") as fasta_file:
#     for _, row in largest_prim_order.iterrows():
#         fasta_file.write(f">{row['seq_id']}|{row['scientific_name']}\n{row['seq']}\n")