In [1]:
# Files
database_file = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt.fasta"
primer_table = "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bmi-primers.tsv"
run_name = 'bmi-50min'
otl_folder = '/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi'

In [2]:
# Intake data
from src.reference_database.sequence_import import *

custom_fasta_import = CustomFastaImport(database_file)
custom_fasta_import.read_fasta(database_file, check_taxid=False)
data = custom_fasta_import.data
data.head()

,seq_id,sequence,length,taxa_info
0,AASFB602-10,AACTTTATATTTAATATTTGGTGTATGATCTGCTATAGCGGGAACA...,658,nan|Ctenidae|family|Animalia|Arthropoda|Arachn...
1,AASFB633-10,TACTTTATATTTAATTTTTGGAGCTTGATCTGCTATAGTTGGAACA...,658,nan|Clubionidae|family|Animalia|Arthropoda|Ara...
2,AASFB645-10,TTCTTTGTATTTATTATTTGGTAGATGATCTGCTATAGTAGGAACA...,658,nan|Anyphaenidae|family|Animalia|Arthropoda|Ar...
3,AASFB649-10,AACTTTATATTTGGTATTTGGGGCTTGATCAGCTATAGTTGGAATA...,658,nan|Corinnidae|family|Animalia|Arthropoda|Arac...
4,AASFB654-10,AACACTTTATTTAGTTTTTGGAGCTTGATCAGCTATAGTTGGTACT...,658,nan|Salticidae|family|Animalia|Arthropoda|Arac...

In [3]:
processed_data = custom_fasta_import.pre_process_harmonized_fasta_database()
processed_data.head()

mozaiko INFO: This method assumes that the FASTA header has been harmonized andcontains the following pipe-separated information:
sequence id, original taxonomy, harmonized taxonomy, rank, kingdom, phylum, class, order, family, genus.

,seq_id,sequence,length,all_taxa_info,original_taxa_info,scientificName,rank,kingdom,phylum,class,order,family,genus,species
0,AASFB602-10,AACTTTATATTTAATATTTGGTGTATGATCTGCTATAGCGGGAACA...,658,nan|Ctenidae|family|Animalia|Arthropoda|Arachn...,nan,Ctenidae,family,Animalia,Arthropoda,Arachnida,Araneae,Ctenidae,NaN,NaN
1,AASFB633-10,TACTTTATATTTAATTTTTGGAGCTTGATCTGCTATAGTTGGAACA...,658,nan|Clubionidae|family|Animalia|Arthropoda|Ara...,nan,Clubionidae,family,Animalia,Arthropoda,Arachnida,Araneae,Clubionidae,NaN,NaN
2,AASFB645-10,TTCTTTGTATTTATTATTTGGTAGATGATCTGCTATAGTAGGAACA...,658,nan|Anyphaenidae|family|Animalia|Arthropoda|Ar...,nan,Anyphaenidae,family,Animalia,Arthropoda,Arachnida,Araneae,Anyphaenidae,NaN,NaN
3,AASFB649-10,AACTTTATATTTGGTATTTGGGGCTTGATCAGCTATAGTTGGAATA...,658,nan|Corinnidae|family|Animalia|Arthropoda|Arac...,nan,Corinnidae,family,Animalia,Arthropoda,Arachnida,Araneae,Corinnidae,NaN,NaN
4,AASFB654-10,AACACTTTATTTAGTTTTTGGAGCTTGATCAGCTATAGTTGGTACT...,658,nan|Salticidae|family|Animalia|Arthropoda|Arac...,nan,Salticidae,family,Animalia,Arthropoda,Arachnida,Araneae,Salticidae,NaN,NaN

In [5]:
database_processed_path = custom_fasta_import.database_fasta_file

In [12]:
insil.primer_table

,target_group,barcode_region,assay_name,fwd_seq,rev_seq,min_read_length,max_read_length,adapter,correct_reverse_primer
0,Arthropod,COI,FwhF2_FwhR2n,GGDACWGGWTGAACWGTWTAYCCHCC,GTRATWGCHCCDGCTARWACWGG,50,551,GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...CC...,CCWGTWYTAGCHGGDGCWATYAC
1,Arthropod,COI,BF3_BR2,CCHGAYATRGCHTTYCCHCG,TCDGGRTGNCCRAARAAYCA,50,560,CCHGAYATRGCHTTYCCHCG;min_overlap=20...TGRTTYTT...,TGRTTYTTYGGNCAYCCHGA
2,Arthropod,COI,FwhF2_EPTDr2n,GGDACWGGWTGAACWGTWTAYCCHCC,CAAACAAATARDGGTATTCGDTY,50,551,GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...RA...,RAHCGAATACCHYTATTTGTTTG
3,Universal,COI,mICOIintF_jgHCO2198,GGWACWGGWTGAACWGTWTAYCCYCC,TAIACYTCIGGRTGICCRAARAAYCA,50,548,GGWACWGGWTGAACWGTWTAYCCYCC;min_overlap=26...TG...,TGRTTYTTYGGICAYCCIGARGTITA
4,Universal,COI,LCO1490_HCO2198,GGTCAACAAATCATAAAGATATTGG,TAAACTTCAGGGTGACCAAAAAATCA,50,549,GGTCAACAAATCATAAAGATATTGG;min_overlap=25...TGA...,TGATTTTTTGGTCACCCTGAAGTTTA
5,Universal,COI,MG2-LCO1490_MG2-univR,TCHACHAAYCAYAARGAYATYGG,ACYATRAARAARATYATDAYRAADGCRTG,50,548,TCHACHAAYCAYAARGAYATYGG;min_overlap=23...CAYGC...,CAYGCHTTYRTHATRATYTTYTTYATRGT
6,Arthropod,COI,fwhF2_Fol-degen-rev,GGDACWGGWTGAACWGTWTAYCCHCC,TANACYTCNGGRTGNCCRAARAAYCA,50,548,GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...TG...,TGRTTYTTYGGNCAYCCNGARGTNTA
7,Universal,COI,MICOIntF_HCO2198,GGWACWGGWTGAACWGTWTAYCCYCC,TAAACTTCAGGGTGACCAAAAAATCA,50,547,GGWACWGGWTGAACWGTWTAYCCYCC;min_overlap=26...TG...,TGATTTTTTGGTCACCCTGAAGTTTA
8,Universal,COI,BF2_BR2,GCHCCHGAYATRGCHTTYCC,TCDGGRTGNCCRAARAAYCA,50,560,GCHCCHGAYATRGCHTTYCC;min_overlap=20...TGRTTYTT...,TGRTTYTTYGGNCAYCCHGA
9,Universal,COI,JgLCO1490_jgHCO2198,TITCIACIAAYCAYAARGAYATTGG,TAIACYTCIGGRTGICCRAARAAYCA,50,549,TITCIACIAAYCAYAARGAYATTGG;min_overlap=25...TGR...,TGRTTYTTYGGICAYCCIGARGTITA

In [11]:
from src.in_silico_analysis.amplification import InSilicoAmplification

insil = InSilicoAmplification(database_processed_path, run_name=run_name)
insil.run_in_silico_analysis(primer_table)

mozaiko INFO: Checking if cutadapt is installed...
mozaiko INFO: cutadapt is installed.
mozaiko INFO: Checking if CRABS is installed...
mozaiko INFO: CRABS is installed.
mozaiko INFO: To continue the analysis, a set of primers is needed. This information should be uploaded as a TSV table and it should contain the following fields: ['target_group', 'barcode_region', 'assay_name', 'fwd_seq', 'rev_seq']
mozaiko INFO: All set. Running in-silico amplification...
mozaiko INFO: Running cutadapt command as: cutadapt -g GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...CCWGTWYTAGCHGGDGCWATYAC;min_overlap=23 --output data/output_data/bmi-50min/amplicon/COI_FwhF2_FwhR2n.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...CCWGTWYTAGCHGGDGCWATYAC;min_overlap=23 --output data/output_data/bmi-50min/insert/COI_FwhF2_FwhR2n.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for FwhF2_FwhR2n.
   --------   1/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g CCHGAYATRGCHTTYCCHCG;min_overlap=20...TGRTTYTTYGGNCAYCCHGA;min_overlap=20 --output data/output_data/bmi-50min/amplicon/COI_BF3_BR2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 560 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g CCHGAYATRGCHTTYCCHCG;min_overlap=20...TGRTTYTTYGGNCAYCCHGA;min_overlap=20 --output data/output_data/bmi-50min/insert/COI_BF3_BR2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 560 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for BF3_BR2.
   --------   2/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...RAHCGAATACCHYTATTTGTTTG;min_overlap=23 --output data/output_data/bmi-50min/amplicon/COI_FwhF2_EPTDr2n.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 551 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...RAHCGAATACCHYTATTTGTTTG;min_overlap=23 --output data/output_data/bmi-50min/insert/COI_FwhF2_EPTDr2n.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 551 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for FwhF2_EPTDr2n.
   --------   3/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g GGWACWGGWTGAACWGTWTAYCCYCC;min_overlap=26...TGRTTYTTYGGICAYCCIGARGTITA;min_overlap=26 --output data/output_data/bmi-50min/amplicon/COI_mICOIintF_jgHCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 548 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g GGWACWGGWTGAACWGTWTAYCCYCC;min_overlap=26...TGRTTYTTYGGICAYCCIGARGTITA;min_overlap=26 --output data/output_data/bmi-50min/insert/COI_mICOIintF_jgHCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 548 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for mICOIintF_jgHCO2198.
   --------   4/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g GGTCAACAAATCATAAAGATATTGG;min_overlap=25...TGATTTTTTGGTCACCCTGAAGTTTA;min_overlap=26 --output data/output_data/bmi-50min/amplicon/COI_LCO1490_HCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 549 --discard-untrimmed --action retain
mozaiko WARNING: No amplicons retrieved for COI_LCO1490_HCO2198.
mozaiko INFO: Running cutadapt command as: cutadapt -g GGTCAACAAATCATAAAGATATTGG;min_overlap=25...TGATTTTTTGGTCACCCTGAAGTTTA;min_overlap=26 --output data/output_data/bmi-50min/insert/COI_LCO1490_HCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 549 --discard-untrimmed --action trim
mozaiko WARNING: No inserts retrieved for COI_LCO1490_HCO2198.
mozaiko INFO: Completed analysis for LCO1490_HCO2198.
   --------   5/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g TCHACHAAYCAYAARGAYATYGG;min_overlap=23...CAYGCHTTYRTHATRATYTTYTTYATRGT;min_overlap=29 --output data/output_data/bmi-50min/amplicon/COI_MG2-LCO1490_MG2-univR.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 548 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g TCHACHAAYCAYAARGAYATYGG;min_overlap=23...CAYGCHTTYRTHATRATYTTYTTYATRGT;min_overlap=29 --output data/output_data/bmi-50min/insert/COI_MG2-LCO1490_MG2-univR.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 548 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for MG2-LCO1490_MG2-univR.
   --------   6/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...TGRTTYTTYGGNCAYCCNGARGTNTA;min_overlap=26 --output data/output_data/bmi-50min/amplicon/COI_fwhF2_Fol-degen-rev.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 548 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g GGDACWGGWTGAACWGTWTAYCCHCC;min_overlap=26...TGRTTYTTYGGNCAYCCNGARGTNTA;min_overlap=26 --output data/output_data/bmi-50min/insert/COI_fwhF2_Fol-degen-rev.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 548 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for fwhF2_Fol-degen-rev.
   --------   7/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g GGWACWGGWTGAACWGTWTAYCCYCC;min_overlap=26...TGATTTTTTGGTCACCCTGAAGTTTA ;min_overlap=27 --output data/output_data/bmi-50min/amplicon/COI_MICOIntF_HCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 547 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g GGWACWGGWTGAACWGTWTAYCCYCC;min_overlap=26...TGATTTTTTGGTCACCCTGAAGTTTA ;min_overlap=27 --output data/output_data/bmi-50min/insert/COI_MICOIntF_HCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 547 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for MICOIntF_HCO2198.
   --------   8/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g GCHCCHGAYATRGCHTTYCC;min_overlap=20...TGRTTYTTYGGNCAYCCHGA;min_overlap=20 --output data/output_data/bmi-50min/amplicon/COI_BF2_BR2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 560 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g GCHCCHGAYATRGCHTTYCC;min_overlap=20...TGRTTYTTYGGNCAYCCHGA;min_overlap=20 --output data/output_data/bmi-50min/insert/COI_BF2_BR2.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 560 --discard-untrimmed --action trim
mozaiko INFO: Completed analysis for BF2_BR2.
   --------   9/10 processed   --------
mozaiko INFO: Running cutadapt command as: cutadapt -g TITCIACIAAYCAYAARGAYATTGG;min_overlap=25...TGRTTYTTYGGICAYCCIGARGTITA;min_overlap=26 --output data/output_data/bmi-50min/amplicon/COI_JgLCO1490_jgHCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 549 --discard-untrimmed --action retain
mozaiko INFO: Running cutadapt command as: cutadapt -g TITCIACIAAYCAYAARGAYATTGG;min_overlap=25...TGRTTYTTYGGICAYCCIGARGTITA;min_overlap=26 --output data/output_data/bmi-50min/insert/COI_JgLCO1490_jgHCO2198.fasta /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/input_data/BMI/bold_idm_filt_processed.fasta --no-indels -e 3 --revcomp --quiet --minimum-length 50 --maximum-length 549 --discard-untrimmed --action trim
mozaiko WARNING: No inserts retrieved for COI_JgLCO1490_jgHCO2198.
mozaiko INFO: Completed analysis for JgLCO1490_jgHCO2198.
   --------   10/10 processed   --------
mozaiko INFO: Number of inserts that were amplified successfully...
    For COI_mICOIintF_jgHCO2198, 2677 were retained.
    For COI_BF2_BR2, 5641 were retained.
    For COI_BF3_BR2, 5688 were retained.
    For COI_MG2-LCO1490_MG2-univR, 6148 were retained.
    For COI_fwhF2_Fol-degen-rev, 2725 were retained.
    For COI_LCO1490_HCO2198, 0 were retained.
    For COI_FwhF2_EPTDr2n, 381947 were retained.
    For COI_MICOIntF_HCO2198, 2006 were retained.
    For COI_JgLCO1490_jgHCO2198, 0 were retained.
    For COI_FwhF2_FwhR2n, 599369 were retained.
mozaiko INFO: Number of inserts with complete PBS that were not amplified...
    For COI_mICOIintF_jgHCO2198: 490341 sequences were retained.
    For COI_BF2_BR2: 494044 sequences were retained.
    For COI_BF3_BR2: 494029 sequences were retained.
    For COI_MG2-LCO1490_MG2-univR: 227859 sequences were retained.
    For COI_fwhF2_Fol-degen-rev: 490653 sequences were retained.
    For COI_LCO1490_HCO2198: 0 sequences were retained.
    For COI_FwhF2_EPTDr2n: 169 sequences were retained.
    For COI_MICOIntF_HCO2198: 490187 sequences were retained.
    For COI_JgLCO1490_jgHCO2198: 0 sequences were retained.
    For COI_FwhF2_FwhR2n: 9584 sequences were retained.
    For COI_mICOIintF_jgHCO2198: 657 sequences were retained.
    For COI_BF2_BR2: 459 sequences were retained.
    For COI_BF3_BR2: 459 sequences were retained.
    For COI_MG2-LCO1490_MG2-univR: 233 sequences were retained.
    For COI_fwhF2_Fol-degen-rev: 619 sequences were retained.
    For COI_LCO1490_HCO2198: 0 sequences were retained.
    For COI_FwhF2_EPTDr2n: 205211 sequences were retained.
    For COI_MICOIntF_HCO2198: 1235 sequences were retained.
    For COI_JgLCO1490_jgHCO2198: 0 sequences were retained.
    For COI_FwhF2_FwhR2n: 8900 sequences were retained.
mozaiko INFO: Number of inserts with incomplete PBS...
    For COI_mICOIintF_jgHCO2198: 490998 sequences were retained.
    For COI_BF2_BR2: 494503 sequences were retained.
    For COI_BF3_BR2: 494488 sequences were retained.
    For COI_MG2-LCO1490_MG2-univR: 228092 sequences were retained.
    For COI_fwhF2_Fol-degen-rev: 491272 sequences were retained.
    For COI_LCO1490_HCO2198: 0 sequences were retained.
    For COI_FwhF2_EPTDr2n: 205380 sequences were retained.
    For COI_MICOIntF_HCO2198: 491422 sequences were retained.
    For COI_JgLCO1490_jgHCO2198: 0 sequences were retained.
    For COI_FwhF2_FwhR2n: 18484 sequences were retained.
mozaiko INFO: In-silico amplification analysis completed.

In [ ]:
from src.marker_scoring.metrics_system import *

output_folder = '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi'

for otl in os.listdir(otl_folder):
    otl_path = os.path.join(otl_folder, otl)

    country_name = otl.split('_')[0]
    output_path = os.path.join(output_folder, country_name + '_ranked_primers.tsv')
    print(" ---------------------")
    print("Processing OTL:", otl)
    mex = MetricsSystemExecutor(results_folder=output_folder, otl=otl_path, primer_table=primer_table)
    ranked_df = mex.rank_primers(save_intermediate_ranks=True, output_path=output_path)
    mex.sort_otl_level_results(subdirectory_name=country_name)

In [2]:
from src.marker_scoring.metrics_system import *

output_folder = '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test'
otl_path = '/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/Sweden_taxonlist_bmi_harmonized.tsv'
output_path = os.path.join(output_folder, 'sweden' + '_ranked_primers.tsv')

mex = MetricsSystemExecutor(results_folder=output_folder, otl=otl_path, primer_table=primer_table)
ranked_df = mex.comprehensive_primer_analysis(output_folder, save_otl_level_results=True)

Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test/amplicon and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: Retrieving primer-PBS statistics.
mozaiko WARNING: No matching amplicon found for insert ID ARCAE215-17 in COI_FwhF2_FwhR2n.fasta
mozaiko WARNING: Empty data in amplicon or insert file for COI_LCO1490_HCO2198.fasta
mozaiko WARNING: Missing data for COI_LCO1490_HCO2198, skipping...
mozaiko WARNING: No matching amplicon found for insert ID BSNHM1352-24 in COI_BF2_BR2.fasta
mozaiko WARNING: No matching amplicon found for insert ID BSNHM1354-24 in COI_BF2_BR2.fasta
mozaiko WARNING: No matching amplicon found for insert ID BSNHM1371-24 in COI_BF2_BR2.fasta
mozaiko WARNING: No matching amplicon found for insert ID CULSA072-19 in COI_BF2_BR2.fasta
mozaiko INFO: Retriving information on the Reference Database Quality.
mozaiko INFO: Calculating the number of barcodes per FASTA.
mozaiko INFO: Calculating the number of barcodes per FASTA.

In [3]:
ranked_df

,barcoded_taxa_one_plus,ratio_barcoded_taxa,mismatch_score,priming_ratio_sum,gc_matches_across_taxon,min_tm_cv,tm_score,amplification_success_percent
primer,,,,,,,,
COI_BF2_BR2,8.57,0.21,107.0,3.00,2.0,3.62,5.83,100.0
COI_LCO1490_HCO2198,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN
COI_FwhF2_FwhR2n,29.17,0.48,1466.0,107.68,0.0,3.31,9.32,100.0

In [ ]:
from src.marker_scoring.metrics_system import *

output_folder = '/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test'
otl_path = '/home/camilababo/Documents/DNAquaIMG/countries-otls/harmonized/bmi/Sweden_taxonlist_bmi_harmonized.tsv'
output_path = os.path.join(output_folder, 'sweden' + '_ranked_primers.tsv')

mex = MetricsSystemExecutor(results_folder=output_folder, otl=otl_path, primer_table=primer_table)
ranked_df = mex.rank_primers(save_intermediate_ranks=True, output_path=output_path)
mex.sort_otl_level_results(subdirectory_name=country_name)

Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test/amplicon and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: Retrieving primer-PBS statistics.
mozaiko WARNING: No matching amplicon found for insert ID ARCAE215-17 in COI_FwhF2_FwhR2n.fasta
mozaiko WARNING: No matching amplicon found for insert ID BSNHM1352-24 in COI_BF2_BR2.fasta
mozaiko WARNING: No matching amplicon found for insert ID BSNHM1354-24 in COI_BF2_BR2.fasta
mozaiko WARNING: No matching amplicon found for insert ID BSNHM1371-24 in COI_BF2_BR2.fasta
mozaiko WARNING: No matching amplicon found for insert ID CULSA072-19 in COI_BF2_BR2.fasta
mozaiko INFO: Retriving information on the Reference Database Quality.
mozaiko INFO: Calculating the number of barcodes per FASTA.
mozaiko INFO: Calculating the number of barcodes per FASTA.
results_folder: /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test, insert_folder_path: None, amplicon_folder_path: None
Set insert_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test/insert/filtered, amplicon_folder_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test/amplicon and incomplete_pbs_path to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test/incomplete_pbs/filtered/filtered_intersection.
mozaiko INFO: MultiBarcodeTools file created to /home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/test/insert/multibarcode/multibarcode_input.tsv

In [1]:
from src.marker_scoring.scoring_utils import *

pbs = extract_primer_binding_sites("/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi/amplicon/COI_FwhF2_FwhR2n.fasta", "/home/camilababo/Documents/coding-projects/DNAquaIMG-tool/mozaico/data/output_data/bmi/insert/COI_FwhF2_FwhR2n.fasta")

In [2]:
pbs[pbs['header'].str.contains("ARCAE215-17")]

,header,fwd_seq,rev_seq,fwd_seq_len,rev_seq_len
11606,>ARCAE215-17|nan|Cyphomyrmex Mayr 1862|genus|A...,GGAACAGGATGAACYGTRTATCCCCC,CCTGTTCTAGCWGGAGCYATTAC,26,23

In [3]:
pbs[pbs['fwd_seq'] == ""]

Empty DataFrame
Columns: [header, fwd_seq, rev_seq, fwd_seq_len, rev_seq_len]
Index: []