# Pre-processing Workflow for diat.barcode Database
diat.barcode Version: 12.4 [('2024-05-28-Diat.barcode_release-version 12.4.xlsx', v17.0)](https://entrepot.recherche.data.gouv.fr/file.xhtml?persistentId=doi:10.57745/O5BFF7&version=17.0), published on 05/06/2024.

This Jupyter Notebook contains all the pre-processing step to extract 2 separate dataset from the original diat.barcode database:
1. diat_barcode-sequence-v12.tsv: This file contains the sequence, sequence ID and the respective species nominal identification.
2. diar_barcode-taxonomy-v12.tsv: This file contains the taxonomic lineage of all the sequences and the respective sequence ID.

In [1]:
# Imports
import pandas as pd

## Read and Exploratory Analysis

In [75]:
diat = pd.read_csv('diat-barcode_v12.tsv', sep='\t', header=0)

/tmp/ipykernel_41683/3584357961.py:1: DtypeWarning: Columns (1,9,28) have mixed types. Specify dtype option on import or set low_memory=False.
  diat = pd.read_csv('diat-barcode_v12.tsv', sep='\t', header=0)

In [76]:
diat.head()

,Sequence ID,GenBank Acc,Sequence,Amplified region,Primer names,Sequencing project,Strain (or sample) sampling ID,Short sequence,Code court de sequence pour fasta,Sequence aligned - rbcl only - aligned june 2021,...,Zig-zag colony,Rosette colony,Ribbon colony,Stellate colony,"arbuscular colony (0: pas observé mais possible, 1: déjà observé)",other kind of colony,High profile guild adapted from Passy (2007) v2,Low profile guild adapted from Passy (2007) v2,Motile guild adapted from Passy (2007) = Mobiles rapides jamais accrochées et biraphidées : Naviculales+Bacillariales (sauf Diadesmis et Diploneis) v2,Euplanctonic guild v2 (centrics)
0,TCC6-18S-1,NaN,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,18S,18S 1F; 18S 528F; 18S 1528R; 18S 1055R,onema,TCC6-27.10.2009,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TCC7a-18S-1,NaN,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,18S,18S 1F; 18S 528F; 18S 1528R; 18S 1055R,@speed-ID,TCC7a-27.10.2009,NaN,NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,TCC9-18S-1,NaN,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,18S,18S 1F; 18S 528F; 18S 1528R; 18S 1055R,@speed-ID,TCC9-22.07.2010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TCC26-18S-1,NaN,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,18S,18S 1F; 18S 528F; 18S 1528R; 18S 1055R,onema,TCC26-22.07.2010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TCC27-18S-1,NaN,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,18S,18S 1F; 18S 528F; 18S 1528R; 18S 1055R,@speed-ID,TCC27-22.07.2010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
diat.tail()

,Sequence ID,GenBank Acc,Sequence,Amplified region,Primer names,Sequencing project,Strain (or sample) sampling ID,Short sequence,Code court de sequence pour fasta,Sequence aligned - rbcl only - aligned june 2021,...,Zig-zag colony,Rosette colony,Ribbon colony,Stellate colony,"arbuscular colony (0: pas observé mais possible, 1: déjà observé)",other kind of colony,High profile guild adapted from Passy (2007) v2,Low profile guild adapted from Passy (2007) v2,Motile guild adapted from Passy (2007) = Mobiles rapides jamais accrochées et biraphidées : Naviculales+Bacillariales (sauf Diadesmis et Diploneis) v2,Euplanctonic guild v2 (centrics)
9229,PP073739,NaN,GCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTATTCCGTA...,rbcl,DPrbcL1-F; DPrbcL7-R; NDrbcL5; 15R,Base-NCBI,NaN,short,PP073739,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9230,PP073741,NaN,TGGGATGCTTCATACGCAGTAAAAACTACTGATGTTCTTGCTTTAT...,rbcl,DPrbcL1-F; DPrbcL7-R; NDrbcL5; 15R,Base-NCBI,NaN,short,PP073741,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9231,PP196581,NaN,TCCAAATACTACAGATCAATACTTCGCTTTCATCGCATACGAATGT...,rbcl,DPrbcL1-F; DPrbcL7-R; NDrbcL5; 15R,Base-NCBI,HYU-D093,short,PP196581,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9232,PP196582,NaN,GCATCTATCATCGGTAACGTATTTGGTTTCAAAGCCGTAGCTGCTT...,rbcl,DPrbcL1-F; DPrbcL7-R; NDrbcL5; 15R,Base-NCBI,HYU-D092,short,PP196582,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
# Get the dataframe shape
diat.shape

(9234, 113)

In [79]:
# Remove columns and rows with all NaN values
diat.dropna(how='all', axis=1, inplace=True)
diat.dropna(how='all', axis=0, inplace=True)

In [80]:
diat.shape

(9234, 113)

In [81]:
# Shape remains the same. However, last row looks to be all NaN values
diat.iloc[-1].isnull().all()

np.False_

In [82]:
# Check columns where values are not NaN in the last row
diat.columns[~diat.iloc[-1].isnull()]

Index(['Benthic', 'Planctonic', 'Epipsamic', 'Epipelic',
       'Wet soil/Bryophytes/Intertidal zone', 'Marine'],
      dtype='object')

In [83]:
# Delete last row
diat.drop(diat.index[-1], inplace=True)

## Extract the sequence dataset

In [84]:
# Select relevant columns
diat_barcode_seq = diat[['Sequence ID', 'Sequence', 'Species']]

In [89]:
# Confirm the selection
diat_barcode_seq.head()

,Sequence ID,Sequence,Species
0,TCC6-18S-1,TAAGCCTGCATGTCTAAGTATAAACTGCTTATACGGTGAAACTGCG...,Chlorogonium elongatum
1,TCC7a-18S-1,TAAGCCTGCATGTCTAAGTATAAATCTCTTACTTTGAAACTGCGAA...,Fragilaria sp.
2,TCC9-18S-1,GTATAAACTGCTATACTGTGAAACTGCGAATGGCTCATTAAATCAG...,Pandorina morum
3,TCC26-18S-1,CTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAG...,Scenedesmus spinosus
4,TCC27-18S-1,TAAACTGCTTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTT...,Scenedesmus quadricauda

In [90]:
# Rename columns for machine readability
diat_barcode_seq.columns = ['seq_ID', 'sequence', 'species']

In [92]:
# Write to file
diat_barcode_seq.to_csv('../../data/input_data/diat_barcode_sequence.tsv', sep='\t', index=False)

## Extract Taxonomy Dataset

In [93]:
col_names = diat.columns.to_list()
# col_names

### Extract Tradicional Taxonomy

In [94]:
# Select columns refering to traditional taxonomy
diat_barcode_tax_1990 = diat[['Sequence ID',
                                'Species',
                                'Genus',
                                'Family (following Round, Crawford & Mann 1990)',
                                'Order (following Round, Crawford & Mann 1990)',
                                'Class (following Round, Crawford & Mann 1990)',
                                'Phylum (following Algaebase 2018)',
                                'Subkingdom (following Algaebase 2018)',
                                'Kingdom (following Algaebase 2018)',
                                'Empire (following Algaebase 2018)']]

In [95]:
# Rename columns for machine readability
diat_barcode_tax_1990.columns = ['seq_ID',
                                'Species',
                                'Genus',
                                'Family',
                                'Order',
                                'Class',
                                'Phylum',
                                'Subkingdom',
                                'Kingdom',
                                'Empire']

In [96]:
diat_barcode_tax_1990.shape

(9233, 10)

In [98]:
diat_barcode_tax_1990.to_csv('../../data/input_data/diat_barcode_taxonomy_1990.tsv', sep='\t', index=False)

### Extract Modern Taxonomy

In [99]:
# Select columns refering to modern taxonomy
diat_barcode_tax_2019 = diat[['Sequence ID',
                                'Species',
                                'Genus',
                                'Family (following Adl et al. 2019)',
                                'Order (following Adl et al. 2019)',
                                'Subclass (following Adl et al. 2019)',
                                'Class (following Adl et al. 2019)',
                                'Subphylum (following Adl et al. 2019)',
                                'Subkingdom (following Adl et al. 2019)',
                                'Kingdom (following Adl et al. 2019)']]

In [100]:
diat_barcode_tax_2019.columns = [['seq_ID',
                                'Species',
                                'Genus',
                                'Family',
                                'Order',
                                'Subclass',
                                'Class',
                                'Subphylum',
                                'Subkingdom',
                                'Kingdom']]

In [101]:
diat_barcode_tax_2019.tail()

,seq_ID,Species,Genus,Family,Order,Subclass,Class,Subphylum,Subkingdom,Kingdom
9228,OX258991,Navicula concordia,Navicula,Naviculaceae,Naviculales,Bacillariophycidae,Bacillariophyceae,Bacillariophytina,Diatomeae,Diatomista
9229,PP073739,Nitzschia nandorii,Nitzschia,Bacillariaceae,Bacillariales,Bacillariophycidae,Bacillariophyceae,Bacillariophytina,Diatomeae,Diatomista
9230,PP073741,Nitzschia nandorii,Nitzschia,Bacillariaceae,Bacillariales,Bacillariophycidae,Bacillariophyceae,Bacillariophytina,Diatomeae,Diatomista
9231,PP196581,Sellaphora pupula,Sellaphora,Sellaphoraceae,Naviculales,Bacillariophycidae,Bacillariophyceae,Bacillariophytina,Diatomeae,Diatomista
9232,PP196582,Amphora copulata,Amphora,Catenulaceae,Thalassiophysales,Bacillariophycidae,Bacillariophyceae,Bacillariophytina,Diatomeae,Diatomista

In [102]:
diat_barcode_tax_2019.shape

(9233, 10)

In [103]:
diat_barcode_tax_2019.to_csv('../../data/input_data/diat_barcode_taxonomy_2019.tsv', sep='\t', index=False)